version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/croissant-webapp"
    ignore:
      # dependabot seems not to support path-based dependencies
      - dependency-name: "croissant-wasm"
    schedule:
      interval: "weekly"
