[package]
name = "croissant-solver-cadical"
version = "0.1.0"
edition = "2021"

[dependencies]
croissant-solver = { path = "../croissant-solver", version = "0.1.0" }
cadical = "0.1.15"

[dev-dependencies]
croissant-crossword = { path = "../croissant-crossword", version = "0.1.0" }