name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust Nightly (for trait upcasting coercion)
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        default: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
